#index:
#    path: /
#    controller: App\Controller\DefaultController::index
indexBack:
  path: /carteBack
  controller: App\Controller\CarteController::indexBack

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
